### ISSUE TITLE
Use php-saml >= 2.10.0

### ISSUE THREAD

**Issue by pitbulk** [Scalr/scalr#81]
[php-saml 2.10.0](https://github.com/onelogin/php-saml/releases/tag/v2.10.0) version.
It includes a security patch that contains extra validations that will prevent signature wrapping attacks and other security improvements.

**Comment by recipe** [comment]
@pitbulk Thank you for heads up. We have introduced SAML support since Scalr Enterprise version 6.0 and this Scalr OS 5.11 version had only limited PoC sand-box without actual connection to Scalr accounts. Actually we planned to update php-saml for Scalr Enterprise and decided to wait for your 2.10.0 release. It will be updated in the upcoming Scalr Enterprise release.
